#!/bin/bash

#
# Wrapper für Tortoise-SVN, um aus der Shell schnell die entsprechenden GUIs 
# für Checkin, -Out, Status aufrufen zu können.
# 
# Die Doku für Tortoise-SVN-Automatisierung:
#
#	https://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-automation.html
#
# Aliase:
#
#	tsvn ci			commit (default: .)
#	tsvn co 		checkout (default: .)
#	tsvn st			status (default .)
#	tsvn up			update (default .)
#	tsvn repo		repobrowser
#
# Kein Alias, dennoch nützlich:
#
#	tsvn log		log (default .)
#
#
# (by) Andreas Heiduk
#

panic() {
	echo 1>&2 "ERROR: $*"
	exit 1
}

[ -z "$1" ] && panic "no command"
case "$1" in
	ci )
		tsvn_cmd=commit
		;;
	co )
		tsvn_cmd=checkout
		;;
	up )
		tsvn_cmd=update
		;;
	st | status )
		tsvn_cmd=repostatus
		;;
	repo )
		tsvn_cmd=repobrowser
		;;
	pl | pg | ps )
		tsvn_cmd=properties
		;;
	* )
		tsvn_cmd="$1"
		;;
esac
shift

if [ "$(uname -o)" = Msys ]; then
	export MSYS_NO_PATHCONV=1
fi

if [ -z "$*" ]; then
	exec TortoiseProc.exe /command:$tsvn_cmd /path:.
else
	exec TortoiseProc.exe /command:$tsvn_cmd /path:"$*"
fi
